# Generated by Django 4.1.3 on 2022-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('date', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
