# Generated by Django 4.1.3 on 2022-11-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
