# Generated by Django 4.1.3 on 2022-11-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogs_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='url',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.TextField(),
        ),
    ]
